version: '2'
services:
  query:
    build: .
#   image: nanopub/query
    restart: unless-stopped
    ports:
      - 9300:9300
      - 9393:9393
    volumes:
      - ./load:/app/load
    environment:
#      - ENDPOINT_TYPE=virtuoso
#      - ENDPOINT=virtuoso:1111
      - USERNAME=dba
      - PASSWORD=dba
      - ENDPOINT_TYPE=rdf4j
      - ENDPOINT=http://rdf4j:8080/rdf4j-server/repositories/test 
      - INIT_WAIT_SECONDS=30
#  virtuoso:
#    image: openlink/virtuoso-opensource-7:latest
#    restart: unless-stopped
#    ports:
#      - 8890:8890
##     - 1111:1111
#    environment:
##     - SPARQL_UPDATE=true
#      - DBA_PASSWORD=dba
#      - VIRT_SPARQL_MaxQueryExecutionTime=600
#      - VIRT_SPARQL_MaxQueryCostEstimationTime=0
#    volumes:
#      - ./data/virtuoso:/database
  rdf4j:
    image: eclipse/rdf4j-workbench:latest
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g
    volumes:
      - ./data/rdf4j/data:/var/rdf4j
      - ./data/rdf4j/logs:/usr/local/tomcat/logs
  nginx:
    image: nginx:alpine
    environment:
      BACKEND: rdf4j:8080
    ports:
      - 8000:80
    volumes:
      - ./nginx/cors-proxy.conf:/etc/nginx/conf.d/default.template:ro
      - ./nginx/yasgui.html:/www/data/tools/yasgui.html
    command:
      - /bin/sh
      - -c
      - envsubst '$$BACKEND' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
        exec nginx-debug -g 'daemon off;'
