services:
  query:
    build: .
    image: nanopub/query
    restart: unless-stopped
    labels:
      "autoheal": "true"
    ports:
      - 9300:9300
      - 9393:9393
    volumes:
      - ./load:/app/load
    environment:
      - ENDPOINT_TYPE=rdf4j
      - ENDPOINT_BASE=http://rdf4j:8080/rdf4j-server/repositories/
#     - INIT_WAIT_SECONDS=120
#     - NANOPUB_QUERY_URL=https://query.knowledgepixels.com/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  autofetch:
    image: alpine
    volumes:
      - ./load:/app/load
      - ./scripts:/app/scripts
    command: /app/scripts/autofetch.sh
  rdf4j:
#   image: eclipse/rdf4j-workbench:5.0.2
    image: nanopub/rdf4j-workbench:5.0.3-SNAPSHOT
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx16g -Xms1g -Xss100m -Dorg.eclipse.rdf4j.client.http.connectionTimeout=10000 -Dorg.eclipse.rdf4j.client.http.connectionRequestTimeout=10000 -Dorg.eclipse.rdf4j.client.http.socketTimeout=10000
    volumes:
      - ./data/rdf4j/data:/var/rdf4j
      - ./data/rdf4j/logs:/usr/local/tomcat/logs
    ports:
      - 8081:8080
  grlc:
    image: clariah/grlc:v1.3.9
    restart: unless-stopped
#   ports:
#     - 8088:80
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  server:
    image: nanopub/server:mongo7
    restart: unless-stopped
    environment:
      - NPS_MONGODB_HOST=mongodb
      - NPS_COLLECT_NANOPUBS_ENABLED=true
      - NPS_POST_NEW_NANOPUBS_TO=http://query:9300
#   ports:
#     - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  servernudger:
    image: alpine
    restart: unless-stopped
    command: sh -c 'while true; do wget -q server:8080 -O /dev/null; sleep 10; done'
  mongodb:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
