version: '2'
services:
  server:
    image: nanopub/server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NPS_MONGODB_HOST=db
      - NPS_COLLECT_NANOPUBS_ENABLED=true
      - NPS_POST_NEW_NANOPUBS_TO=http://query:9300
    ports:
      - 8080:8080
  db:
    image: nanopub/mongo
    #image: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/dbb
  query:
    image: nanopub/query
    restart: unless-stopped
    ports:
      - 9300:9300
      - 9393:9393
    volumes:
      - ./load:/app/load
    environment:
      - ENDPOINT_TYPE=rdf4j
      - ENDPOINT_BASE=http://rdf4j:8080/rdf4j-server/repositories/ 
      - INIT_WAIT_SECONDS=30
  rdf4j:
    image: eclipse/rdf4j-workbench:latest
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx1g -Xms1g
    volumes:
      - ./data/rdf4j/data:/var/rdf4j
      - ./data/rdf4j/logs:/usr/local/tomcat/logs
